name: CPA
checkpoint: null
device: cuda

kwargs:
  n_latent: 84
  recon_loss: gauss
  pert_embeddings: null
  hidden_dim: 256 # not used
  n_hidden_encoder: 768
  n_layers_encoder: 3
  n_hidden_decoder: 768
  n_layers_decoder: 3
  use_batch_norm: decoder
  use_layer_norm: encoder
  dropout_rate_encoder: 0.15
  dropout_rate_decoder: 0.15
  n_hidden_adv: 64
  n_layers_adv: 2
  use_norm_adv: batch
  dropout_rate_adv: 0.2
  variational: False
  expr_transform: none
  seed: 2025
  cell_sentence_len: 1
  residual_decoder: false
  nb_decoder: false
  encode_dosage: false
  dosage_non_linearity: identity